name       : alabaster
version    : 0.7.10
release    : 4
source     :
    - https://pypi.org/packages/source/a/alabaster/alabaster-0.7.10.tar.gz : 37cdcb9e9954ed60912ebc1ca12a9d12178c26637abdf124e3cde2341c257fe0
license    : BSD-3-Clause
component  : programming.python
summary    : Alabaster is a visually (c)lean, responsive, configurable theme for the
    Sphinx documentation system.
description: |
    Alabaster is a visually (c)lean, responsive, configurable theme for the Sphinx documentation system.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
