name       : alabaster
version    : 0.7.8
release    : 1
source     :
    - https://github.com/bitprophet/alabaster/archive/0.7.8.tar.gz : ebfea26e1a6d459432d995717316ab786ebc8bd43d859228e5bea31b3ebd2a32
license    : BSD-3-Clause
component  : programming.python
summary    : Alabaster is a visually (c)lean, responsive, configurable theme for the Sphinx documentation system.
description: |
    Alabaster is a visually (c)lean, responsive, configurable theme for the Sphinx documentation system.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
