name       : alabaster
version    : 0.7.11
release    : 5
source     :
    - https://files.pythonhosted.org/packages/3f/46/9346ea429931d80244ab7f11c4fce83671df0b7ae5a60247a2b588592c46/alabaster-0.7.11.tar.gz : b63b1f4dc77c074d386752ec4a8a7517600f6c0db8cd42980cae17ab7b3275d7
license    : BSD-3-Clause
component  : programming.python
summary    : Alabaster is a visually (c)lean, responsive, configurable theme for the Sphinx documentation system.
description: |
    Alabaster is a visually (c)lean, responsive, configurable theme for the Sphinx documentation system.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
